general:
  stop_time: 30 sec
  seed: 1
  parallelism: 4
  bootstrap_end_time: 0 sec
  log_level: info
  heartbeat_interval: 1 sec
  data_directory: shadow.data
  template_directory: null
  progress: false
  model_unblocked_syscall_latency: true
network:
  graph:
    type: gml
    inline: |
      graph [
        directed 0
        node [
          id 0
          host_bandwidth_up "1000 Gbit"
          host_bandwidth_down "1000 Gbit"
        ]
        edge [
          source 0
          target 0
          latency "1 us"
          packet_loss 0.0
        ]
      ]
  use_shortest_path: true
experimental:
  use_sched_fifo: false
  use_syscall_counters: true
  use_object_counters: true
  use_preload_libc: true
  use_preload_openssl_rng: true
  use_preload_openssl_crypto: false
  use_memory_manager: false
  use_cpu_pinning: true
  use_worker_spinning: true
  runahead: 1 ms
  use_dynamic_runahead: false
  socket_send_buffer: 131072 B
  socket_send_autotune: true
  socket_recv_buffer: 174760 B
  socket_recv_autotune: true
  interface_qdisc: fifo
  strace_logging_mode: off
  max_unapplied_cpu_latency: 1 μs
  unblocked_syscall_latency: 1 μs
  unblocked_vdso_latency: 10 ns
  scheduler: thread-per-core
  report_errors_to_stderr: true
  use_new_tcp: false
  native_preemption_enabled: false
  native_preemption_native_interval: 100 ms
  native_preemption_sim_interval: 10 ms
hosts:
  time-test-baseline:
    network_node_id: 0
    processes:
    - path: ./time_benchmark
      args: '100000'
      environment: {}
      start_time: 5 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: null
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  time-test-frequent:
    network_node_id: 0
    processes:
    - path: ./time_benchmark
      args: '1000000'
      environment: {}
      start_time: 1 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: null
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
