general:
  stop_time: 3 min
  seed: 1
  parallelism: 16
  bootstrap_end_time: 0 sec
  log_level: warning
  heartbeat_interval: 1 sec
  data_directory: shadow.data
  template_directory: null
  progress: false
  model_unblocked_syscall_latency: false
network:
  graph:
    type: gml
    inline: |
      graph [
        directed 0
        node [
          id 0
          host_bandwidth_up "1000 Gbit"
          host_bandwidth_down "1000 Gbit"
        ]
        edge [
          source 0
          target 0
          latency "1 us"
          packet_loss 0.0
        ]
      ]
  use_shortest_path: true
experimental:
  use_sched_fifo: false
  use_syscall_counters: true
  use_object_counters: true
  use_preload_libc: true
  use_preload_openssl_rng: true
  use_preload_openssl_crypto: false
  use_memory_manager: false
  use_cpu_pinning: true
  use_worker_spinning: true
  runahead: 1 ms
  use_dynamic_runahead: false
  socket_send_buffer: 131072 B
  socket_send_autotune: true
  socket_recv_buffer: 174760 B
  socket_recv_autotune: true
  interface_qdisc: fifo
  strace_logging_mode: off
  max_unapplied_cpu_latency: 1 μs
  unblocked_syscall_latency: 1 μs
  unblocked_vdso_latency: 10 ns
  scheduler: thread-per-core
  report_errors_to_stderr: true
  use_new_tcp: false
  native_preemption_enabled: false
  native_preemption_native_interval: 100 ms
  native_preemption_sim_interval: 10 ms
hosts:
  create-network-db:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/scripts/create-network-db.sh
      args: ''
      environment: {}
      start_time: 5 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: null
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  geth-account:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/go-ethereum/build/bin/geth
      args: account new --datadir /home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/execution --password /home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/geth_password.txt
      environment: {}
      start_time: 12 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: null
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  geth-bootnode:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/go-ethereum/build/bin/bootnode
      args: -genkey /home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/bootnode/nodekey
      environment: {}
      start_time: 8 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/go-ethereum/build/bin/bootnode
      args: -nodekey /home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/bootnode/nodekey -addr=11.0.0.3:30301 -verbosity=9
      environment: {}
      start_time: 10 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: 11.0.0.3
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  geth-genesis:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/go-ethereum/build/bin/geth
      args: init --datadir=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/execution /home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/execution/genesis.json
      environment: {}
      start_time: 14 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: null
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  geth-node:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/go-ethereum/build/bin/geth
      args: --networkid=32382 --http --http.api=eth,net,web3 --http.addr=0.0.0.0 --http.corsdomain="*" --http.port=8000 --port=8400 --metrics.port=8300 --ws --ws.api=eth,net,web3 --ws.addr=0.0.0.0 --ws.origins="*" --ws.port=8100 --authrpc.vhosts="*" --authrpc.addr=0.0.0.0 --authrpc.jwtsecret=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/execution/jwtsecret --authrpc.port=8200 --datadir=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/execution --password=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/geth_password.txt --identity=node-0 --maxpendpeers=0 --verbosity=3 --syncmode=full --ipcdisable --nodiscover --maxpeers=0 --nat=none
      environment: {}
      start_time: 16 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: 11.0.0.10
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  prysm-beacon-1:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/prysm/bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain
      args: --datadir=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/consensus/beacondata --min-sync-peers=0 --p2p-max-peers=5 --genesis-state=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/consensus/genesis.ssz --interop-eth1data-votes --chain-config-file=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/consensus/config.yml --contract-deployment-block=0 --chain-id=32382 --rpc-host=11.0.0.20 --rpc-port=4000 --grpc-gateway-host=11.0.0.20 --grpc-gateway-port=4100 --execution-endpoint=http://11.0.0.10:8200 --accept-terms-of-use --jwt-secret=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/execution/jwtsecret --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524 --minimum-peers-per-subnet=0 --p2p-tcp-port=4200 --p2p-udp-port=4300 --p2p-host-ip=11.0.0.20 --monitoring-port=4400 --verbosity=info --bootstrap-node=enode://1234567890123456789012345678901234567890123456789012345678901234@11.0.0.3:30301
      environment: {}
      start_time: 21 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: 11.0.0.20
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  prysm-beacon-2:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/prysm/bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain
      args: --datadir=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/node-2/consensus/beacondata --min-sync-peers=0 --p2p-max-peers=5 --genesis-state=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/node-2/consensus/genesis.ssz --interop-eth1data-votes --chain-config-file=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/node-2/consensus/config.yml --contract-deployment-block=0 --chain-id=32382 --rpc-host=11.0.0.21 --rpc-port=4001 --grpc-gateway-host=11.0.0.21 --grpc-gateway-port=4101 --execution-endpoint=http://11.0.0.10:8200 --accept-terms-of-use --jwt-secret=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/execution/jwtsecret --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524 --minimum-peers-per-subnet=0 --p2p-tcp-port=4201 --p2p-udp-port=4301 --p2p-host-ip=11.0.0.21 --monitoring-port=4401 --verbosity=info --peer=/ip4/11.0.0.20/tcp/4200/p2p/16Uiu2HAmFdE3HSicMFV8Tp2568e3kpJ76iZCmL26MsURJgCY7KLj --bootstrap-node=enode://1234567890123456789012345678901234567890123456789012345678901234@11.0.0.3:30301
      environment: {}
      start_time: 21 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: 11.0.0.21
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  prysm-genesis:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/prysm/bazel-bin/cmd/prysmctl/prysmctl_/prysmctl
      args: testnet generate-genesis --fork=deneb --num-validators=10 --chain-config-file=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/config.yml --geth-genesis-json-in=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/genesis.json --output-ssz=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/genesis.ssz --geth-genesis-json-out=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/genesis.json
      environment: {}
      start_time: 1 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: null
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  prysm-validator-1:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/prysm/bazel-bin/cmd/validator/validator_/validator
      args: --beacon-rpc-provider=11.0.0.20:4000 --datadir=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/consensus/validatordata --accept-terms-of-use --interop-num-validators=5 --interop-start-index=0 --rpc-port=7000 --grpc-gateway-port=7100 --monitoring-port=7200 --graffiti="node-0" --chain-config-file=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/the-node/consensus/config.yml
      environment: {}
      start_time: 26 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: 11.0.0.30
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  prysm-validator-2:
    network_node_id: 0
    processes:
    - path: /home/ins0/Learning/Testnet/LocalTry/ethereum-pos-testnet/dependencies/prysm/bazel-bin/cmd/validator/validator_/validator
      args: --beacon-rpc-provider=11.0.0.21:4001 --datadir=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/node-2/consensus/validatordata --accept-terms-of-use --interop-num-validators=5 --interop-start-index=5 --rpc-port=7000 --grpc-gateway-port=7100 --monitoring-port=7200 --graffiti="node-1" --chain-config-file=/home/ins0/Learning/Shadow-Test/Test-Alpha/05-testnet-full/network/node-2/consensus/config.yml
      environment: {}
      start_time: 26 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: 11.0.0.31
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
